# Generated by Django 3.1.6 on 2021-02-06 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210206_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=100, verbose_name='Slug'),
        ),
    ]
